spring:
  application:
    name: catalog
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      uri: mongodb://localhost:27017/catalog
      database: catalog
      auto-index-creation: true

server:
  port: 8002

eureka:
  client:
    enabled: ${EUREKA_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
