spring.application.name=notification
server.port=8008
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.enabled=${SPRING_CLOUD_CONFIG_ENABLED:false}

eureka.client.enabled=${EUREKA_ENABLED:true}
eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

management.endpoints.web.exposure.include=health,info
