spring:
  application:
    name: inventory
  datasource:
    # Changed to 15432 to match your docker-compose host port
    url: jdbc:postgresql://localhost:15432/switchscale_db 
    username: postgres
    password: ${DB_PASSWORD:abc123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      # Redisson will use these properties by default