spring.application.name=cart
server.port=8004
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.enabled=${SPRING_CLOUD_CONFIG_ENABLED:false}

eureka.client.enabled=${EUREKA_ENABLED:false}

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.show-sql=false

spring.cloud.openfeign.client.config.default.connectTimeout=2000
spring.cloud.openfeign.client.config.default.readTimeout=3000

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=cart_group
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.switchscale.order.Event,com.switchscale.cart.event
spring.kafka.consumer.properties.spring.json.value.default.type=com.switchscale.cart.event.OrderPlacedEvent

management.endpoints.web.exposure.include=health,info
