spring.application.name=eureka-server
server.port=8761
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
spring.cloud.config.enabled=${SPRING_CLOUD_CONFIG_ENABLED:false}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

management.endpoints.web.exposure.include=health,info
